# Generated by Django 3.0.4 on 2020-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200306_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='value_entry',
            field=models.IntegerField(),
        ),
    ]
