# Generated by Django 3.0.4 on 2020-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200308_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='value_entry',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
